<?php
/**
 * @file
 * Code for the kidneys_spe module.
 */

/**
 * HOW TO ADD A NEW LEARNING MODULE
 *
 * Through Drupal Admin:
 * 1) Determine any new assessment fields and add to spe entityform.
 * 2) Add these same fields to the Patient Profile content type.
 * 3) Create any new Patient Profiles associated with this module.
 * 4) Update existing Patient Profiles to configure any of the fields
 *    added in step 2. Usually these new fields values are not important
 *    for existing profiles so all values should be selected. (this stinks).
 * 5) Add any Knowledge Unit content needed and associate with new Profiles.
 * 6) Add a new Course content for this Learning Module as well as any
 *    Sections for this course.
 * 7) Add the Knowledge Units to the section(s).
 *
 * In Code:
 * 1) Update hook_theme for any new template files, should be for the
 *    new Learning Module's form page and results page, and maybe results section,
 *    can omit this to use default templates.
 * 2) Update kidneys_spe_assessment_fields to specify the fields used for
 *    this new version's assessment form.
 * 3) Update kidneys_spe_form to set the appropriate template for the form page.
*/

include_once 'kidneys_spe.features.inc';



/**
 * Implementation of hook_preprocess_page.
 */
function kidneys_spe_preprocess_page(&$vars) {

  // This is really nkf_base theme specific.
  // Unset a few layout things.
  $alias = strtolower(drupal_get_path_alias());
  if (strpos($alias, 'phi') !== FALSE) {
    // Get rid of title and make contents full width.
    $vars['has_title'] = false;
    $vars['widescreen'] = true;
    // Set the top nav to white.
    if (function_exists('nkf_base_color_theme_helper')) {
      $vars['th'] = nkf_base_color_theme_helper('white');
    }
  }
}
/*
 * Implementation of hook_theme.
 * TODO: review that we need all these.
 */
function kidneys_spe_theme($existing, $type, $theme, $path){
  return array(
    'kidney_spe_full_score' => array(
      'template' => 'kidneys-spe-full-score',
      'path' => drupal_get_path('module', 'kidneys_spe') . '/templates',
      'type' => 'theme',
      'preprocess functions' => array('kidneys_spe_full_score_preprocess'),
      'override preprocess functions' => TRUE,
      'variables' => array(
        'title' => NULL,
        'content' => NULL
      ),
    ),
    'kidneys_spe_form_page' => array(
      'template' => 'kidneys-spe-form-page',
      'path' => drupal_get_path('module', 'kidneys_spe') . '/templates',
      'type' => 'theme',
      'preprocess functions' => array('kidneys_spe_form_page_preprocess'),
      'override preprocess functions' => TRUE,
      'variables' => array(
        'title' => NULL,
        'content' => NULL
      ),
    ),
    'kidneys_spe_form_page_health' => array(
      'template' => 'kidneys-spe-form-page-health',
      'path' => drupal_get_path('module', 'kidneys_spe') . '/templates',
      'type' => 'theme',
      'preprocess functions' => array('kidneys_spe_form_page_health_preprocess'),
      'override preprocess functions' => TRUE,
      'variables' => array(
        'title' => NULL,
        'content' => NULL
      ),
    ),
    'kidneys_spe_form_page_gout' => array(
      'template' => 'kidneys-spe-form-page-gout',
      'path' => drupal_get_path('module', 'kidneys_spe') . '/templates',
      'type' => 'theme',
      'preprocess functions' => array('kidneys_spe_form_page_gout_preprocess'),
      'override preprocess functions' => TRUE,
      'variables' => array(
        'title' => NULL,
        'content' => NULL
      ),
    ),
    'kidneys_spe_risk_page' => array(
      'template' => 'kidneys-spe-risk-page',
      'path' => drupal_get_path('module', 'kidneys_spe') . '/templates',
      'type' => 'theme',
      'preprocess functions' => array('kidneys_spe_risk_page_preprocess'),
      'override preprocess functions' => TRUE,
      'variables' => array(
        'title' => NULL,
        'content' => NULL
      ),
    ),
    'kidneys_spe_health_page' => array(
      'template' => 'kidneys-spe-health-page',
      'path' => drupal_get_path('module', 'kidneys_spe') . '/templates',
      'type' => 'theme',
      'preprocess functions' => array('kidneys_spe_health_page_preprocess'),
      'override preprocess functions' => TRUE,
      'variables' => array(),
    ),
    'kidneys_spe_gout_page' => array(
      'template' => 'kidneys-spe-gout-page',
      'path' => drupal_get_path('module', 'kidneys_spe') . '/templates',
      'type' => 'theme',
      'preprocess functions' => array('kidneys_spe_gout_page_preprocess'),
      'override preprocess functions' => TRUE,
      'variables' => array(),
    ),
    'kidneys_spe_hyperk_page' => array(
      'template' => 'kidneys-spe-hyperk-page',
      'path' => drupal_get_path('module', 'kidneys_spe') . '/templates',
      'type' => 'theme',
      'preprocess functions' => array('kidneys_spe_hyperk_page_preprocess'),
      'override preprocess functions' => TRUE,
      'variables' => array(),
    ),
    'kidneys_spe_course_sections_page' => array(
      'template' => 'kidneys-spe-course-sections-page',
      'path' => drupal_get_path('module', 'kidneys_spe') . '/templates',
      'type' => 'theme',
      'preprocess functions' => array('kidneys_spe_course_sections_page_preprocess'),
      'override preprocess functions' => TRUE,
      'variables' => array(),
    ),
    'kidneys_spe_course_one_section_page' => array(
      'template' => 'kidneys-spe-course-one-section-page',
      'path' => drupal_get_path('module', 'kidneys_spe') . '/templates',
      'type' => 'theme',
      'preprocess functions' => array('kidneys_spe_course_one_section_page_preprocess'),
      'override preprocess functions' => TRUE,
      'variables' => array(),
    ),
    'kidneys_spe_course_section_page' => array(
      'template' => 'kidneys-spe-course-section-page',
      'path' => drupal_get_path('module', 'kidneys_spe') . '/templates',
      'type' => 'theme',
      'preprocess functions' => array('kidneys_spe_course_section_page_preprocess'),
      'override preprocess functions' => TRUE,
      'variables' => array(),
    ),
    'kidneys_spe_list_accordion' => array(
      'template' => 'kidneys-spe-list-accordion',
      'path' => drupal_get_path('module', 'kidneys_spe') . '/templates',
      'type' => 'theme',
      'variables' => array(
        'title' => NULL,
        'items' => NULL,
      ),
    ),
    'kidneys_spe_list_accordion_item' => array(
      'template' => 'kidneys-spe-list-accordion-item',
      'path' => drupal_get_path('module', 'kidneys_spe') . '/templates',
      'type' => 'theme',
      'variables' => array(
        'title' => NULL,
        'description' => NULL,
        'iid' => NULL,
      ),
    ),
    'kidneys_spe_card_pic' => array(
      'template' => 'kidneys-spe-card-pic',
      'path' => drupal_get_path('module', 'kidneys_spe') . '/templates',
      'type' => 'theme',
      'variables' => array(
        'title' => NULL,
      ),
    ),
    'kidneys_spe_card_badge' => array(
      'template' => 'kidneys-spe-card-badge',
      'path' => drupal_get_path('module', 'kidneys_spe') . '/templates',
      'type' => 'theme',
      'variables' => array(
        'title' => NULL,
      ),
    ),
  );
}

/**
 * Returns the fields to include for the assessment based on the version.
 *
 * @param string $version
 *  The version of the assessment. This value ususally comes from
 *  a URL parameter or is a field on a "course" content type.
 *
 * @return array
 *  An array of field names to include in the entityform.
 */
function kidneys_spe_assessment_fields($version = 'health') {
  // Load all field names for personalize health form.
  $field_info = field_info_instances('entityform', 'personalized_health_form');
  // Hack to add height field.
  $field_info['field_height'] = true;
  $fields = array();
  switch ($version) {
    case 'gout':
      $fields = array(
        'field_spe_ckd_diagnosis',
        'field_spe_gout_diagnosis',
        'field_spe_gout_symptoms',
        'field_spe_gout_uric_acid_level'
      );
      break;
    case 'hyperk':
      $fields = array(
        'field_spe_ckd_diagnosis',
        'field_spe_pot_diagnosis',
        'field_spe_pot_symptoms',
        'field_spe_pot_level'
      );
      break;
    case 'health':
    default:
      $fields = array(
        'field_spe_diabetes_diagnosis',
        'field_spe_prediabetes_diagnosis',
        'field_spe_htx_diagnosis',
        'field_spe_heart_disease',
        'field_spe_family_history',
        'field_spe_ckd_diagnosis',
        'field_spe_on_dialysis',
        'field_spe_had_transplant',
        'field_spe_height_feet',
        'field_spe_height_inches',
        'field_height',
        'field_spe_weight',
        'field_spe_egfr',
        'field_spe_acr',
      );
      break;
  }
  // Loop through fields to make sure they actually exist.
  foreach($fields as $i => $field) {
    if (!isset($field_info[$field])) {
      unset($fields[$i]);
    }
  }
  return $fields;
}

/**
 * Implements hook_form_alter
 */
function kidneys_spe_form_alter(&$form, &$form_state, $form_id) {

 if ($form_id == 'personalized_health_form_entityform_edit_form') {
   // Get the form version from the url.
   // There is probably a better way to do this.
   $get = drupal_get_query_parameters();
   $version = isset($get['version']) ? $get['version'] : 'health';

   // Add the version to the form for later use.
   $form['spe_version'] = array(
      '#type' => 'hidden',
      '#value' => $version,
    );

   // Add a submit handler which will deal with appropriate
   // redirection based on version. This is for both new and updated
   // forms. Might want to exclude this when working from admin UI.
   $form['actions']['submit']['#submit'][] = 'kidneys_spe_form_submit';
   $form['actions']['save']['#submit'][] = 'kidneys_spe_form_submit';

   // These fields are shared with the patient profile but here
   // we want them to be single select so we make them radios.
   $make_radios = array(
     'field_spe_family_history'
     , 'field_spe_ckd_diagnosis'
     , 'field_spe_htx_diagnosis'
     , 'field_spe_diabetes_diagnosis'
     , 'field_spe_prediabetes_diagnosis'
     , 'field_spe_on_dialysis'
     , 'field_spe_egfr'
     , 'field_spe_acr'
     , 'field_spe_had_transplant'
     , 'field_spe_heart_disease'
     , 'field_spe_gout_diagnosis'
     , 'field_spe_gout_symptoms'
     , 'field_spe_gout_uric_acid_level'
     , 'field_spe_pot_diagnosis'
     , 'field_spe_pot_level'
   );

   foreach($make_radios as $field) {
     $form[$field][LANGUAGE_NONE]['#type'] = 'radios';
     // Ensure they are set to single value.
     $form[$field][LANGUAGE_NONE]['#multiple'] = FALSE;
     // Make sure these fields are required.
     // And set the attribute as this doen't seem to be
     // set automatically but is needed for js validation.
     $form[$field][LANGUAGE_NONE]['#required'] = TRUE;
     $form[$field][LANGUAGE_NONE]['#attributes']['class'][] = 'required';
     // Defaults work differntly on radios, need a single value, not array.
     if (empty($form_state['values']) && !empty($form[$field][LANGUAGE_NONE]['#default_value'])) {
       $default = reset($form[$field][LANGUAGE_NONE]['#default_value']);
       $form[$field][LANGUAGE_NONE]['#default_value'] = $default;
     }
   }
   // Tweak height display.
   $height_weight = array(
     'field_spe_height_feet'
     , 'field_spe_height_inches'
   );
   $form['field_height'] = array(
     '#type' => 'item'
     , '#title' => $form['field_spe_height_feet'][LANGUAGE_NONE]['#title']
     , '#required' => TRUE
     , '#attributes' => array('class' => array('grid'))
     , '#weight' => $form['field_spe_height_feet']['#weight']
   );
   $form['#group_children']['field_height'] = $form['#group_children']['field_spe_height_feet'];
   foreach ($height_weight as $field) {
     $form[$field][LANGUAGE_NONE][0]['value']['#title_display'] = 'invisible';
     $form[$field]['#attributes']['class'][] = 'grid-cell padding-right--xs';
     $form['field_height'][$field] = $form[$field];
     unset($form[$field]);
   }
   // Remove any unwanted fields based on the assessment version.
   // Get fields to show based on form "version".
   // Right now the version is stored in a get parameter.
   $fields_to_include = kidneys_spe_assessment_fields($version);
   $captcha_group;
   $captcha_group_index = 0;
   foreach(element_children($form) as $field) {
     // Make sure we are just looking at "field" form elements.
     if (substr($field, 0, 5) == 'field') {
       if (array_search($field, $fields_to_include) === FALSE) {
         unset($form[$field]);
       } else {
         // Figure out the last field group so we can inject captcha.
         if (isset($form['#group_children'][$field])
          && $form['#groups'][$form['#group_children'][$field]]->weight > $captcha_group_index) {
           $captcha_group_index = $form['#groups'][$form['#group_children'][$field]]->weight;
           $captcha_group = $form['#group_children'][$field];
         }
       }
     }
   }
   // Add reCAPTCHA.
   if (module_exists('captcha') && module_exists('recaptcha')) {
     $form['captcha'] = array(
      '#type' => 'captcha',
      '#captcha_type' => 'recaptcha/reCAPTCHA',
      '#weight' => 999,
      '#attributes' => array(
        'data-callback' => 'testing',
        'class' => array('testing')
      ),
      //'#prefix' => '<div class="padding-top--lg padding-x--xs text-align--center">',
      //'#suffix' => '</div>'
     );
     $form['#group_children']['captcha'] = $captcha_group;
   }

   // Hide form actions greater than sm breakpoint to let js-based
   // form advancement take over. This is hacky and we should do somewhere else.
   $form['actions']['#prefix'] = '<div class="sm--hide padding-x--xxxl padding-y--md">';
   $form['actions']['#suffix'] = '</div>';
   $form['actions']['submit']['#attributes']['class'][] = 'width--100 button--yellow caps bold';
 }
}

/**
 * Implements hook_form_submit
 */
function kidneys_spe_form_submit($form, &$form_state) {
  if (!empty($entityform = $form_state['entityform']) && !empty($entityform->entityform_id)) {
    // If there is a specific version redirect to that page.
    $values = $form_state['values'];
    $version = !empty($values['spe_version']) ? $values['spe_version'] : 'health';
    $form_state['redirect'] = url('phi/' . $entityform->entityform_id . '/' . $version);
  }
}

/**
 * Implements hook_menu().
 */
function kidneys_spe_menu() {
  $items['phi/form'] = array(
    'title callback' => 'kidney_spe_form_title',
    'page callback' => 'kidneys_spe_form',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['phi/%/%'] = array(
    'title callback' => 'kidney_spe_results_title',
    'title arguments' => array(1, 2),
    'page callback' => 'kidneys_spe_page',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['phi/%/%/%node'] = array(
    'title' => '',
    'page callback' => 'kidneys_spe_section_page',
    'page arguments' => array(1, 2, 3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Callback to get title for form page.
 */
 function kidney_spe_form_title() {
   $get = drupal_get_query_parameters();
   $version = isset($get['version']) ? $get['version'] : NULL;
   switch ($version) {
     case 'gout':
        return t('Gout Health Assessment');
     case 'health':
        return t('Kidney Health Assessment');
     default:
        return t(ucfirst($version) . ' Health Assessment');
    }
}
/**
 * Callback to get title for results page.
 */
 function kidney_spe_results_title($id, $version) {
   switch ($version) {
     case 'gout':
        return t('Gout Health Results');
     case 'health':
        return t('Kidney Health Results');
     default:
        return t(ucfirst($version) . ' Health Results');
   }
 }

/**
 * Callback for main SPE form page.
 */
function kidneys_spe_form($entity_id = FALSE) {
  // Include js for cookies...yum.
  drupal_add_library('system', 'jquery.cookie');
  $path = drupal_get_path('module', 'kidneys_spe');
  drupal_add_js($path . '/js/kidneys_spe.js');
  drupal_add_css($path . '/css/kidneys_spe.css');

  // Just a variable to hold theme values.
  $return = array();

  // Do we have an existing entity form submission or is this
  // a new submission?
  $get = drupal_get_query_parameters();
  $entity_id = isset($get['id']) ? $get['id'] : FALSE;

  // Get the entityform for new or update.
  $form = kidneys_spe_get_form($entity_id);

  // The entityform already knows what verson based on hook_form_alter
  // but we will use this below.
  $version = isset($get['version']) ? strtolower($get['version']) : 'health';

  // The course node is connected with a version, so lets get it.
  $course = kidneys_spe_get_course_by_code($version);

  // TODO: review...We might no longer need these as we are crafting each
  // learning module's experience in template files.
  if ($course) {
    $form_header = field_get_items('node', $course, 'field_spe_course_form_header');
    $form_header = field_view_value('node', $course, 'field_spe_course_form_header', $form_header[0]);
    $form_subheader = field_get_items('node', $course, 'field_spe_course_form_sub_header');
    $form_subheader = field_view_value('node', $course, 'field_spe_course_form_sub_header', $form_subheader[0]);
  }

  // Get all our template variables ready.
  Global $base_url;
  $return = array(
    'form' => $form,
    'version' => $version,
    'form_header' => render($form_header),
    'form_subheader' => render($form_subheader),
    'module_path' => drupal_get_path('module', 'kidneys_spe'),
    'path' => $base_url . request_uri()
  );

  // Figure out which theme template file to use based on version.
  switch ($version) {
    case 'health':
      $theme = 'kidneys_spe_form_page_health';
      break;
    case 'gout':
      $theme = 'kidneys_spe_form_page_gout';
      break;
    case 'risk':
      $theme = 'kidneys_spe_form_page_health';
      break;
    case 'hyperk!':
      $theme = 'kidneys_spe_hyperk_page';
      break;
    default:
      $theme = 'kidneys_spe_form_page';
      break;
  }

  return theme($theme, $return);
}

/**
 * Returns an entity from for inserting or updating an entityform submission.
 *
 * @param int $entity_id
 *  The optional ID for an entity form submission.
 *
 * @return string
 *  The rendered entityform form.
 */
function kidneys_spe_get_form($entity_id = FALSE) {
  $type = 'personalized_health_form';
  $entity_form = entityform_type_load($type);
  if ($entity_form && entityform_access('submit', $entity_form)) {
    module_load_include('inc', 'entityform', 'entityform.admin');
    if ($entity_id) {
      $entity = entityform_load($entity_id);
      $form = entityform_form_wrapper($entity, 'edit', 'embedded');
    } else {
      $form = entityform_form_wrapper(entityform_empty_load($type), 'submit', 'embedded');
    }

    // Remove elements we don't want to display.
    $form['redirect']['#access'] = FALSE;
    $form['user_info']['#access'] = FALSE;
    return drupal_render($form);
  } else {
    return null;
  }
}

/**
 * Returns page for results menu.
 *
 * @param int $entityformid
 *  The ID for an entity form submission.
 *
 * @param string $version
 *  Learning Module version code name.
 *
 * @return string
 *  The rendered page.
 */
function kidneys_spe_page($entityformid, $version) {

  // Include js for cookies...yum.
  drupal_add_library('system', 'jquery.cookie');
  drupal_add_js(array(
    'kidneys_spe' => array(
      'assessments' => array($version => $entityformid),
    ),
  ), 'setting');
  $path = drupal_get_path('module', 'kidneys_spe');
  drupal_add_js($path . '/js/kidneys_spe.js');
  drupal_add_css($path . '/css/kidneys_spe.css');

  $version = strtolower($version);

  // Get all course information (title, sections, etc.)
  $course = kidneys_spe_get_course_by_code($version);
  if (!$course) {
    $course = kidneys_spe_get_course_by_code('health');
  }
  $course_wrapper = entity_metadata_wrapper('node', $course);
  $course_title = $course_wrapper->title->value();
  $course_description = kidneys_spe_get_rendered_field('node', $course, 'body');
  $course_sections = $course_wrapper->field_spe_course_sections->value();

  // Get full assessment data and load relevant profiles (ie. archetypes)
  $submission = entity_metadata_wrapper('entityform', $entityformid);
  $profiles = kidneys_spe_get_profiles_from_assessment($entityformid);

  // Add profile names to variable for admin debugging.
  foreach($profiles as $profile) {
    $profile_names[] = '<li>' . $profile->title;
  }
  $profile_names = '<ul>' . implode($profile_names, '') .'</ul>';

  // Set some basic variables for emailing results.
  // TODO: do we still need this?
  $link = url('phi/' .$entityformid . '/' . $version, array('absolute'=>true));
  $body = 'Thank you for taking the health assessment. You can find find your results here: ' . $link;
  $query = array(
   'subject' => 'National Kidney Foundation Health Assessment',
   'body' => $body,
  );

  Global $base_url;
  // This will be our return variable that gets piped into the template file.
  $return = array(
   'submission' => $submission,
   'profiles' => $profiles,
   'profile_names' => $profile_names,
   'submission_id' => $entityformid,
   'email' => url('mailto:', array('query' => $query)),
   'course_title' => $course_title,
   'course_description' => $course_description,
   'module_path' => drupal_get_path('module', 'kidneys_spe'),
   'path' => $base_url . request_uri()
  );

  // These are the two important labs, they are special for determining which version
  // of the tool the user gets.
  $gfr = !empty($submission->field_spe_egfr) ? $submission->field_spe_egfr[0]->value() : 'unk';
  $acr = !empty($submission->field_spe_acr) ? $submission->field_spe_acr[0]->value() : 'unk';
  $return['gfr'] = $gfr;
  $return['acr'] = $acr;
  // Use the 'risk' version of the tool because it was set by the 'version'
  // or we don't have gfr or acr.
  if ($version == 'risk' || ($version == 'health' && ($grf == 'unk' || $acr == 'unk'))) {
    // Set version to risk because we don't know enough about the person.
    $version = 'risk';

    // Get list of risk factors from view.
    $risk_factors = views_get_view_result('spe_knowledge_units', 'risk_factors', $entityformid);

    // List of risk factor slugs, these are set on the node,
    // we use them here for ordering and to specify the risk 'type'.
    $slugs = array(
      'diabetes'=>'common'
      , 'hypertension'=>'common'
      , 'heart'=>'common'
      , 'familyhistory'=>'common'
      , 'obese'=>'additional'
      , 'prediabetes'=>'additional'
    );

    // Set some defaults for the theme variables.
    $return['common_factors_count'] = 0;
    $return['additional_factors_count'] = 0;
    $items = array();
    foreach($risk_factors as $value) {
      $slug = $value->field_field_base_slug[0]['raw']['value'];
      $i = array_search($slug, array_keys($slugs));

      // This requires the nkf_base theme to work/
      // TODO: we should decouple this.
      $items[$i] = theme('kidneys_spe_card_badge', array(
        'title'=> render($value->node_title),
        'teaser'=> $value->field_body[0]['rendered']['#markup'],//render($value->field_body),
        'badge' => !empty($value->field_field_spe_icon) ? render($value->field_field_spe_icon) : NULL,
      ));

      // Count up our different risk factors
      if ($slugs[$slug] == 'common') {
        ++$return['common_factors_count'];
      }
      if ($slugs[$slug] == 'additional') {
        ++$return['additional_factors_count'];
      }
    }
    ksort($items);

    // Determine the appropriate scenario, which will determine the specific output.
    // scenario 1: > 0 common factors, no or good Labs, no diagnosis
    // scenario 2: = 0 common factors, > 0 additional factors, no or good Labs, no diagnosis
    // scenario 3: risk factors don't matter, bad Labs, no diagnosis
    // scenario 4: risk factors & labs don't matter, affirmative diagnosis
    // scenario 5: > 0 factors, no or good Labs, no diagnosis
    $return['scenario'];
    // First, check for scenario 4.
    if ($submission->field_spe_ckd_diagnosis[0]->value() == 'yes') {
      $return['scenario'] = 4;
      // Check scenario 3.
    } elseif($gfr !== 'unk' && $acr !== 'unk' && kidneys_spe_get_health_score($gfr, $acr) !== 'good') {
      $return['scenario'] = 3;
      // Check scenario 5.
    } elseif($return['common_factors_count'] == 0 && $return['additional_factors_count'] == 0) {
      $return['scenario'] = 5;
      // Check scenario 1.
    } elseif($return['common_factors_count'] > 0) {
      $return['scenario'] = 1;
      // Final option is 2.
    } else {
      $return['scenario'] = 2;
    }
    // Set remaining theme variables and theme function.
    $return['risk_factors'] = $items;
    $return['risk_factors_items'] = $items;
    $return['factor_count'] = count($risk_factors);
    $return['total_factors'] = 5;
    $theme = 'kidneys_spe_risk_page';

    // We are not using 'risk' version but only have one section associated
    // with our course (e.g. gout module).
  } elseif(count($course_sections) == 1) {
    // If we have a single section course just land on a detail page
    $section = $course_sections[0];

    //Get icon for section.
    $return['icon'] = kidneys_spe_get_rendered_field('node', $section, 'field_spe_icon');

    // Load the KUs for the section, and theme them.
    $kus = views_get_view_result('spe_kus_by_section_and_profile', 'default', $entityformid, $section->nid);
    $items = kidneys_spe_ku_accordion($kus, TRUE, $entityformid);
    $return['knowledge_units'] = theme('kidneys_spe_list_accordion', array('items' => $items, 'classes' => 'bg--white'));

    // Get any Action style KUs and theme.
    // This might need to be rethought, do we want this to come from the
    // section or just any action knowledge units for the version/profile(s)?
    $actions = views_get_view_result('spe_knowledge_units', 'all', $entityformid, 1);
    $actions = kidneys_spe_ku_simple_render($actions);
    $return['actions'] = render($actions);

    // Set a promo_banner, dependent on nkf_base theme
    // and only needed if we don's have a specific theme for this module.
    $return['header'] = theme('promo_banner', array(
      'title' => $course_title,
      'body' => '',
      'video' => kidneys_spe_get_rendered_field('node', $course, 'field_base_video'),
      'image' => kidneys_spe_get_rendered_field('node', $course, 'field_base_image'),
    ));

  // Move on to a course with multiple sections (e.g. 'health')
  } elseif(count($course_sections) > 1) {

    // TODO: document this block.
    $sections = kidneys_spe_get_course_sections_by_assessment($course, $entityformid);
    $items = array();
    $j = 1;
    foreach($sections as $i => $section) {
      $items[] = kidneys_spe_section_card($section, $entityformid, $version, $j);
      $j++;
    }

    $actions = views_get_view_result('spe_knowledge_units', 'all', $entityformid, 1);
    $actions = kidneys_spe_ku_accordion($actions);
    $return['actions'] = theme('kidneys_spe_list_accordion', array('items' => $actions, 'classes' => 'bg--white'));
    $return['sections'] = $items;

    $return['type'] = $health = kidneys_spe_get_health_score($gfr, $acr);
    $return['color'] = kidneys_spe_get_health_color($health['score']);
    $return['video'] =kidneys_spe_get_rendered_field('node', $course, 'field_base_video');
    $return['header'] = theme('promo_banner', array(
      'title' => $course_title,
      'body' => 'Need some text',
      'video' => kidneys_spe_get_rendered_field('node', $course, 'field_base_video'),
      'image' => kidneys_spe_get_rendered_field('node', $course, 'field_base_image'),
      'ctas' => array(
        array('button'=>'button--orange', 'url'=>'#course-sections','title'=>'Course sections'),
        array('button'=>'button--outline--orange', 'url'=>'#course-desc','title'=>'About the course'),
      )
    ));

    //$theme = 'kidneys_spe_course_sections_page';
  }
  // Set the theme. TODO: place this in config section.
  if (!isset($theme)) {
    switch ($version) {
      case 'gout':
        $theme = 'kidneys_spe_gout_page';
        break;
      case 'risk':
        $theme = 'kidneys_spe_risk_page';
        break;
      case 'health':
        $theme = 'kidneys_spe_health_page';
        break;
      case 'hyperk':
        $theme = 'kidneys_spe_hyperk_page';
        break;
      default:
        $theme = 'kidneys_spe_risk_page';
        break;
    }
  }
  $return['version'] = $version;
  return theme($theme, $return);
}

/**
 * Returns page for section menu item.
 *
 * @param int $entityformid
 *  The ID for an entity form submission.
 *
 * @param string $version
 *  Learning Module version code name.
 *
 * @param node $section
 *  Section node.
 *
 * @return string
 *  The rendered page.
 */
function kidneys_spe_section_page($entityformid, $version, $section) {
  // TODO: document this function.

  $path = drupal_get_path('module', 'kidneys_spe');
  drupal_add_js($path . '/js/kidneys_spe.js');
  drupal_add_css($path . '/css/kidneys_spe.css');

  $return = array();
  $version = strtolower($version);
  $course = kidneys_spe_get_course_by_code($version);
  $sections = kidneys_spe_get_course_sections_by_assessment($course, $entityformid);
  $section_keys = array_flip(array_keys($sections));
  $section_values = array_values($sections);
  $previous_section = $section_values[$section_keys[$section->nid]-1];
  if($previous_section) {
    //$previous_section = l($previous_section->title, 'phi/'. $entityformid . '/' . $version . '/' . $previous_section->nid);
    $previous_section = l(t('Previous Section'), 'phi/'. $entityformid . '/' . $version . '/' . $previous_section->nid);
  }
  $return['previous_section'] = $previous_section;
  $next_section = $section_values[$section_keys[$section->nid]+1];
  if($next_section) {
    //$next_section = l($next_section->title, 'phi/'. $entityformid . '/' . $version . '/' . $next_section->nid);
    $next_section = l(t('Next Section'), 'phi/'. $entityformid . '/' . $version . '/' . $next_section->nid);
  }
  $j = 1;
  foreach($sections as $s) {
    $options = array(
      'html' => TRUE,
      'attributes' => array('class' =>
        array(
          'color--gray-4',
          'rounded',
          'display--block',
          'padding-y--xxs',
          'padding-x--xs')
        )
    );
    if($s->nid == $section->nid) {
        //$options['attributes']['style']= 'background: #F9B357;';
        $options['attributes']['class'][] = 'truncate brush--orange';
    }

    $t = '<span class="font-size--lg bold">' . $j . '</span> <span class="font-size--md">'. $s->title . '</span>';
    $return['section_links'][] = l(t($t), 'phi/'. $entityformid . '/' . $version . '/' . $s->nid, $options);
    $j++;
  }
  $return['next_section'] = $next_section;
  $return['sections'] = $sections;

  $return['course_home'] = url('phi/'. $entityformid . '/' . $version);
  $return['course_title'] = $course->title;
  $return['title'] = $section->title;
  $return['description'] = kidneys_spe_get_rendered_field('node', $section, 'body');
  $return['icon'] = kidneys_spe_get_rendered_field('node', $section, 'field_spe_icon');
  //$return['period'] = kidneys_spe_get_rendered_field('node', $section, 'field_spe_section_period');
  $return['period'] = 'Section ' . ($section_keys[$section->nid] + 1);
  $kus = views_get_view_result('spe_kus_by_section_and_profile', 'info', $entityformid, $section->nid);
  $items = kidneys_spe_ku_accordion($kus, TRUE, $entityformid);
  $actions = views_get_view_result('spe_kus_by_section_and_profile', 'action_track', $entityformid, $section->nid);
  $actions_items = kidneys_spe_ku_accordion($actions);
  $return['has_actions'] = !empty($actions_items);
  $return['knowledge_units'] = theme('kidneys_spe_list_accordion', array('items' => $items, 'classes' => 'bg--white'));
  $return['actions_track'] = theme('kidneys_spe_list_accordion', array('items' => $actions_items, 'classes' => 'bg--white'));
  return theme('kidneys_spe_course_section_page', $return);

}

/**
 * Helper function to get sections by Course and Profile.
 */
function kidneys_spe_get_course_sections_by_assessment($course, $entityformid) {
  $course_wrapper = entity_metadata_wrapper('node', $course);
  $course_sections = $course_wrapper->field_spe_course_sections->value();
  $sections_by_profile = views_get_view_result('spe_course_sections_by_profile', 'default', $entityformid, $course->nid);
  $sections = array();
  foreach($sections_by_profile as $i => $value) {
    $section = reset(array_filter($course_sections, function($item) use($value){
      return ($item->nid == $value->nid);
    }));
    $sections[$section->nid] = $section;
  }
  return $sections;
}

/**
 * Helper function to set accordion display for KUs
 */
function kidneys_spe_ku_accordion($kus, $tracking = false, $entityformid = false) {
  $items = array();
  $iid = user_password();
  foreach($kus as $i => $value) {
    // TODO: figure out why rendering adds some broken html on certain multidevs
    //$desc = drupal_render($value->field_body);
    $desc = $value->field_body[0]['rendered']['#markup'];
    if ($tracking && function_exists('nkf_misc_get_rate_widget')) {
      $v = ($entityformid) ? $entityformid : NULL;
      $rating = nkf_misc_get_rate_widget('ku-nid: ' . $value->nid, $v);
      $desc .= $rating;
    }
    // TODO: actually make this work.
    /*$desc .= '<div class="print--hide display--flex padding-top--md justify-content--space-between align-items--center">';
    $desc .= ($tracking) ? '<a href="#" class="button--orange">mark done</a>' : '';
    $desc .= '<div class="">';
    $desc .= '<span class="bold">Is this content useful? </span>';
    $desc .= '<a  href="#">Yes</a> <a href="#">No</a></div>';
    $desc .= '</div>';
    */
    $items[] = theme('kidneys_spe_list_accordion_item', array(
      'title'=> render($value->node_title),
      'description'=> $desc,
      'iid' => $iid . '-' . $i,
      'first' => ($i == 0) ? TRUE : FALSE,
      'category' => 'ku-nid: ' . $value->nid,
      'value' => $v,
    ));
  }
  return $items;
}

/**
 * Helper function to render KUs
 */
function kidneys_spe_ku_simple_render($kus, $tracking = false) {
  $items = array();
  foreach($kus as $i => $value) {

    $desc = $value->field_body[0]['rendered']['#markup'];
    $title = '<div class="bold">'.render($value->node_title).'</div>';
    $items[] = $title.$desc;
  }
  return implode($items,'');
}

/**
 * Helper function to display card for Section.
 */
function kidneys_spe_section_card($section, $entityformid, $version, $i) {

  $image_path = drupal_get_path('module', 'kidneys_spe') . '/images/';

  $desc = kidneys_spe_get_rendered_field('node', $section, 'body');
  $teaser = '<div class="padding-bottom--md">'.$desc.'</div>';
  $section_path = url('phi/'. $entityformid . '/' . $version . '/' .$section->nid);
  $period = kidneys_spe_get_rendered_field('node', $section, 'field_spe_section_period');
  $card = theme('kidneys_spe_card_badge', array(
    'title_prefix' => ($i) ? 'section '. $i : 'section y',
    'title'=> $section->title,
    //'teaser'=> $teaser,
    'path' => $section_path,
    'badge' => kidneys_spe_get_rendered_field('node', $section, 'field_spe_icon')
    //'badge' => '/' . $image_path . 'khicon_ckd.png'
  ));
  return $card;
}


/*
 * Helper function that gets a course node by the version code name.
 */
function kidneys_spe_get_course_by_code($code) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'spe_course')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_spe_code_name', 'value', $code, '=')
    ->range(0, 1);
  $result = $query->execute();
  if (isset($result['node'])) {
    $nid = reset(array_keys($result['node']));
    $course = entity_load_single('node', $nid);
    return $course;
  } else {
    return NULL;
  }
}



/**
 * Return array of profile entities from entityform id.
 *
 * @param int $entityform
 *  Entityform ID, but also takes Entityform object.
 *
 * @return array
 *  Array of profile nodes.
 */
function kidneys_spe_get_profiles_from_assessment($entityform) {

  // Make sure we are dealing with the ID and not an object.
  $id = is_object($entityform) ? $entityform->entityform_id : $entityform;

  // Static function cacheing for speedy return.
  $data = &drupal_static(__FUNCTION__ . $id, FALSE);

  if (empty($data)) {
    // Get wrapper for entityform submission.
    $submission = entity_metadata_wrapper('entityform', $entityform);

    if (!empty($submission->value())) {
      // Load field names for entityform.
      $instances = field_info_instances('entityform', 'personalized_health_form');

      // Loop thru submission fields and assemble query clauses
      // based on the submission values
      $fields = array();
      foreach ($instances as $field_name => $instance) {
        $value = $submission->{$field_name}->value();
        // Some field values are stored as arrays
        // and some are not...deal with it by only
        // taking the first value. This requires that all
        // assessment answers allow for only one value,
        // this should be changed.
        if (is_array($value)) {
          if (count($value) > 0) {
            $value = $value[0];
          } else {
            $value = NULL;
          }
        }
        $fields[$field_name] = $value;
      }

      // Remove height and weight field values but add in BMI.
      if (isset($fields['field_spe_weight'])
          && isset($fields['field_spe_height_feet'])
          && isset($fields['field_spe_height_inches'])) {
        $fields['field_spe_bmi']
          = kidneys_spe_get_bmi(
            $fields['field_spe_weight'],
            $fields['field_spe_height_feet'],
            $fields['field_spe_height_inches']);
      }
      unset($fields['field_spe_weight']);
      unset($fields['field_spe_height_feet']);
      unset($fields['field_spe_height_inches']);

      // Get all Patient Profile nodes.
      // This could get troublesome with many nodes.
      // TODO: set so we are only pulling profiles
      // that have at least one non-null value for
      // submissions that have those values.
      $query = new EntityFieldQuery();
      $query->entityCondition('entity_type', 'node');
      $query->entityCondition('bundle', 'patient_profile');
      $query->propertyCondition('status', NODE_PUBLISHED);
      $query->addMetaData('account', user_load(1));
      foreach ($fields as $field_name => $value) {
        if (!empty($value)) {
          //$query->fieldCondition($field_name, 'value', NULL, '!=');
        }
      }
      $result = $query->execute();

      $relevant_profiles = array();
      if (isset($result['node'])) {
        $nids = array_keys($result['node']);
        $profiles = node_load_multiple($nids);

        // Loop through all profiles to weed out the
        // irrelevant ones.
        foreach ($profiles as $nid => $profile) {
          // This variable will be determine if the form submission
          // connects with this profile.
          $include = true;

          // Loop through each field value from the form
          // to see if the values match the profile.
          foreach (array_keys($fields) as $field_name) {
            $profile_values = array();
            // If the profile has values for submission field
            // we need to evaluate if they match.
            if (count($profile->{$field_name}) > 0) {
              // Gather up all the values to check.
              foreach ($profile->{$field_name}[LANGUAGE_NONE] as $value) {
                $profile_values[$value['value']] = $value['value'];
              }
            } else {
              // If the profile doesn't have a value that corrolates
              // with a submission field than we won't exclude the profile.
              // Inclusion and exclusion are affirmative.
              continue;
            }
            // If our profile has a value set for a field
            // but the submission doesn't match one of those values
            // we exclude the profile.
            if (!isset($profile_values[$fields[$field_name]])) {
              $include = FALSE;
              // One fail and we are outa' here.
              break;
            }
          }
          // Add included profiles to our list
          if ($include) $relevant_profiles[$profile->nid] = $profile;
        }
        $data = $relevant_profiles;
      } else {
        $data = FALSE;
      }
    } else {
      $data = FALSE;
    }
  }
  return $data;
}

/**
 * Return array of profile entities from entityform id.
 *
 * @param int $entityform
 *  Entityform ID, but also takes Entityform object.
 *
 * @param string $version
 *  Version code name to limit the query clauses.
 *
 * @return array
 *  Array of profile nodes.
 */
function kidneys_spe_get_profiles_from_assessmentOLD($entityform, $version = NULL) {

  // Make sure we are dealing with the ID and not an object.
  $id = is_object($entityform) ? $entityform->entityform_id : $entityform;

  // Static function cacheing for speedy return.
  $data = &drupal_static(__FUNCTION__ . $id, FALSE);

  if (empty($data)) {
    // Get wrapper for entityform submission.
    $submission = entity_metadata_wrapper('entityform', $entityform);

    if (!empty($submission->value())) {
      // Load field names for entityform.
      $instances = field_info_instances('entityform', 'personalized_health_form');

      // Limit criteria to select version.
      if (isset($version)) {
        $version_fields = kidneys_spe_assessment_fields($version);
        $instances = array_intersect_key($instances, array_flip($version_fields));
      }

      // Set up profile query.
      $query = new EntityFieldQuery();
      $query->entityCondition('entity_type', 'node');
      $query->entityCondition('bundle', 'patient_profile');
      $query->propertyCondition('status', NODE_PUBLISHED);
      $query->addMetaData('account', user_load(1));

      // Loop thru submission fields and assemble query clauses
      // based on the submission values
      $fields = array();

      foreach ($instances as $field_name => $instance) {
        $value = $submission->{$field_name}->value();
        // Some field values are stored as arrays
        // and some are not...deal with it by only
        // taking the first value. This requires that all
        // assessment answers get only one value.
        if (is_array($value)) {
          if (count($value) > 0) {
            $value = $value[0];
          } else {
            $value = NULL;
          }

        }
        $fields[$field_name] = (string) $value;
      }

      // Remove height and weight field values but add in BMI.
      if (isset($fields['field_spe_weight'])
          && isset($fields['field_spe_height_feet'])
          && isset($fields['field_spe_height_inches'])) {
        $fields['field_spe_bmi']
          = kidneys_spe_get_bmi(
            $fields['field_spe_weight'],
            $fields['field_spe_height_feet'],
            $fields['field_spe_height_inches']);
      }
      unset($fields['field_spe_weight']);
      unset($fields['field_spe_height_feet']);
      unset($fields['field_spe_height_inches']);

      foreach ($fields as $field_name => $value) {
        if (!empty($value)) {
          $query->fieldCondition($field_name, 'value', $value, '=');
        }
      }
      $result = $query->execute();
      if (isset($result['node'])) {
        $data = node_load_multiple($nids);
      } else {
        $data = FALSE;
      }
    } else {
      $data = FALSE;
    }
  }
  return $data;
}

/**
 * Implements hook_field_widget_form_alter().
 */
function kidneys_spe_field_widget_form_alter(&$element, &$form_state, $context) {

  // Move the help text into the label for gout symptoms.
  if (isset($element['#entity_type']) &&
      $element['#entity_type'] == 'entityform' &&
      $element['#bundle'] == 'personalized_health_form' &&
      $element['#field_name'] == 'field_spe_gout_symptoms') {
    $element['#title'] = '<div>' . $element['#title'] . '</div>' . $element['#description'];
    $element['#description'] = '';
  }

}

/**
 * Implements hook_views_pre_view().
 */
function kidneys_spe_views_pre_view(&$view, &$display_id, &$args) {
  // If we have specific views, take the entityform ID
  // and swap out matching profile IDs.
  if (($view->name == 'spe_knowledge_units'
      || $view->name == 'spe_sections'
      || $view->name == 'spe_kus_by_section_and_profile'
      || $view->name == 'spe_course_sections_by_profile'
      || $view->name == 'spe_categories_by_profile_2') ){
    if (!empty($view->args)) {
      $arg_0 = $view->args[0];
      $entityformid = reset(explode('+', $arg_0));
      if ($entityformid != 'all') {
        $profiles = kidneys_spe_get_profiles_from_assessment($entityformid);
        if ($profiles) {
          $view->args[0] = implode('+', array_keys($profiles));
        }
      }
    }
  }
}

/**
 * Helper function to calculate BMI.
 *
 * @param $weight float Weight in lbs.
 * @param $height_feet.
 * @param $height_inches.
 *
 * @return float
 */
function kidneys_spe_get_bmi($weight, $height_feet, $height_inches) {
  $inches = $height_feet * 12 + $height_inches;
  $bmi = ($weight / pow($inches,2)) * 703;
  $ranges = list_allowed_values(field_info_field('field_spe_bmi'));
  foreach(array_keys($ranges) as $range) {
    $i = explode('_', $range);
    if ($i[0] <= $bmi && $bmi < $i[1]) {
      return $range;
    }
  }
  return FALSE;
}


/**
 * Return health rating from acr and gfr
 *
 * @param $gfr string
 * @param $acr string
 *
 * @return
 */
function kidneys_spe_get_health_score($gfr, $acr) {
  $map = array(
    '90_1000' => array(
      '300_1000'  => array('score' => 35, 'name' => 'poor to fair'),
      '30_299'    => array('score' => 55, 'name' => 'fair to good'),
      '0_29'      => array('score' => 85, 'name' => 'good'),
    ),
    '60_89' => array(
      '300_1000'  => array('score' => 35, 'name' => 'poor to fair'),
      '30_299'    => array('score' => 55, 'name' => 'fair to good'),
      '0_29'      => array('score' => 80, 'name' => 'good'),
    ),
    '45_59' => array(
      '300_1000'  => array('score' => 25, 'name' => 'poor'),
      '30_299'    => array('score' => 40, 'name' => 'poor to fair'),
      '0_29'      => array('score' => 50, 'name' => 'fair'),
    ),
    '30_44' => array(
      '300_1000'  => array('score' => 20, 'name' => 'poor'),
      '30_299'    => array('score' => 45, 'name' => 'poor to fair'),
      '0_29'      => array('score' => 40, 'name' => 'poor to fair'),
    ),
    '15_29' => array(
      '300_1000'  => array('score' => 15, 'name' => 'poor'),
      '30_299'    => array('score' => 15, 'name' => 'poor'),
      '0_29'      => array('score' => 15, 'name' => 'poor'),
    ),
    '0_14' => array(
      '300_1000'  => array('score' => 15, 'name' => 'poor'),
      '30_299'    => array('score' => 15, 'name' => 'poor'),
      '0_29'      => array('score' => 15, 'name' => 'poor'),
    ),
  );
  if ($gfr === 'unk' || $acr === 'unk') {
    return FALSE;
  }
  $return = $map[$gfr][$acr];
  $return['type'] = 'health';
  $return['scale'] = array('Good Health', 'fair Health', 'Poor Health');

  return $return;
}


/**
 *
 *
 *
 *
 */
 function kidneys_spe_get_health_color($p, $reverse = FALSE) {
   if ($reverse) {
     if ($p > 50) {
       $rgb_end = array(213,18,23);
       $rgb_beginning = array(254,220,0);
       $p = ($p - 50) / 50;
     } else {
       $rgb_end = array(254,220,0);
       $rgb_beginning = array(1, 130, 65);
       $p = $p / 50;
     }
   } else {
     if ($p <= 50) {
       $rgb_beginning = array(213,18,23);
       $rgb_end = array(254,220,0);
       $p = $p / 50;
     } else {
       $rgb_beginning = array(254,220,0);
       $rgb_end = array(1, 130, 65);
       $p = ($p - 50) / 50;
     }
   }

   $w = $p * 2 - 1;

   $w1 = ($w + 1) / 2.0;
   $w2 = 1 - $w1;

   $rgb = array(
     intval($rgb_beginning[0] * $w2 + $rgb_end[0] * $w1),
     intval($rgb_beginning[1] * $w2 + $rgb_end[1] * $w1),
     intval($rgb_beginning[2] * $w2 + $rgb_end[2] * $w1)
   );
   $hex = "#";
   $hex .= str_pad(dechex($rgb[0]), 2, "0", STR_PAD_LEFT);
   $hex .= str_pad(dechex($rgb[1]), 2, "0", STR_PAD_LEFT);
   $hex .= str_pad(dechex($rgb[2]), 2, "0", STR_PAD_LEFT);
   return $hex;
 };

/**
 * Helper function to return rendered field.
 */
function kidneys_spe_get_rendered_field($entity_type, $entity, $field_name, $delta = 0) {
  $field = field_get_items($entity_type, $entity, $field_name);
  if (!empty($field)) {
    $output = field_view_value($entity_type, $entity, $field_name, $field[$delta]);
    return render($output);
  } else {
    return NULL;
  }
}


/**
 * Implements hook_flag_alter
 */
 /*
function kidneys_spe_flag_alter(&$flag) {
  //dpm($flag, 'hook_flag_alter');
  watchdog('hook_flag_alter', '<pre>'.print_r($flag,1).'</pre>');
  // Get the submission ID from the url and store for later user.
  $args = explode('/', current_path());
  if (isset($args[1])) {
    // TODO check that this is an ID of an entityform submission.
    $flag->kidneys_spe_id = $args[1];
  }
}
*/
/**
 * Implements hook_flag_flag
 */
 /*
function kidneys_spe_flag_flag($flag, $entity_id, $account, $flagging) {
  //dpm($flag, 'hook_flag_flag');
  watchdog('hook_flag_flag', '<pre>'.print_r($flag,1).'</pre>');
  $args = explode('/', current_path());
  if (isset($args[0]) && $args[0] === 'phi' && isset($args[1])) {
    // TODO set value of related submission.
    // Loads the entity found and creates or updates a field value.
    $this_flag = entity_load_single('flagging', $flag->fid);
    $this_flag->field_spe_related_assessment['und'][0]['value'] = $args[1];

    // Saves the updated flagging entity object
    entity_save('flagging', $this_flag);
    watchdog('hook_flag_flag_this', '<pre>'.print_r($this_flag,1).'</pre>');
  }
}
*/




/**
 * Implements hook_rate_vote_alter.
 */
function kidneys_spe_rate_vote_alter($votes, $context) {
  //watchdog('spe_rate_votes', '<pre>'.print_r($votes,1).'</pre>');
  //watchdog('spe_rate_context', '<pre>'.print_r($context,1).'</pre>');
  //watchdog('spe_rate_rpath', '<pre>'.print_r($_SERVER['HTTP_REFERER'],1).'</pre>');
}
